### ISSUE TITLE
Custom styles for paper-dialog-title should be after ::slotted(*:first-child)

### ISSUE THREAD

**Issue by NoLdman** [PolymerElements/paper-dialog-behavior#118]
### Description
In Polymer v2.0 the styling block `:host > ::slotted(h2)` was moved above `:host > ::slotted(*:first-child)`, as described [here](https://github.com/PolymerElements/paper-dialog-behavior/blob/2f3b60cbd63c251f939289af82cf8ed89439c3af/paper-dialog-shared-styles.html#L55).

The problem with that solution is, if you want to apply a custom `margin-top` to the title (h2), the margin won't change. Therefore I think `@apply --paper-dialog-title;` should be moved to an additional styling block beneath `:host > ::slotted(*:last-child)`. See:

```css
:host > ::slotted(h2) {
  position: relative;
  margin: 0;
  @apply --paper-font-title;
}

:host > ::slotted(*:first-child) {
  margin-top: 24px;
}


:host > ::slotted(*:last-child) {
  margin-bottom: 24px;
}

:host > ::slotted(h2) {
  @apply --paper-dialog-title;
}
```

### Expected outcome

The margin-top selector should match the set style within `--paper-dialog-title`.

### Actual outcome

The margin-top won't change, even if you apply a `margin-top` within `--paper-dialog-title`.

### Live Demo
Example: https://jsbin.com/seyusejefe/edit?html,output

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 11
- [x] Edge
- [x] IE 11

**Comment by valdrinkoshi** [comment]
@NoLdman good catch! Indeed, the current setup won't allow to easily setup the margin for `<h2>` if that's done through the mixin, but you can still do it by directly styling the `<h2>`, e.g.
```css
h2 {
  margin-top: 0;
}
```
https://jsbin.com/dewiboh/1/edit?html,output

That said, I still think it's beneficial to move the `@apply --paper-dialog-title`, which will allow styling all paper-dialogs across shadowRoots, e.g. https://jsbin.com/loyokuc/1/edit?html,output
