### ISSUE TITLE
Styles that use * are specific enough

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-dialog-behavior#21]
I have a reset stylesheet in my main page. The selector `:host > ::content > * ` is never not specific enough under shady dom and that styles are never applied:

<img width="406" alt="screen shot 2015-08-03 at 10 36 46 am" src="https://cloud.githubusercontent.com/assets/238208/9043615/98cffbd2-39cb-11e5-9a3c-13c2c3d608c6.png">
yles

**Comment by valdrinkoshi** [comment]
The only solution i can think of is applying the style like this:
```css
:host > ::content > *,
:host > ::content > h2,
:host > ::content > div,
:host > ::content > p {
  margin-top: 20px;
  padding: 0 24px;
}
```

but is far from ideal...any other ideas?
