### ISSUE TITLE
Nesting paper-toolbar in paper-dialog causes alignment issues

### ISSUE THREAD

**Issue by blasten** [PolymerElements/paper-dialog-behavior#35]
From https://github.com/PolymerElements/paper-toolbar/issues/38
__paper-dialog-behavior__ is adding margin: https://github.com/PolymerElements/paper-dialog-behavior/blob/master/paper-dialog-common.css#L13  should it do it?

**Comment by valdrinkoshi** [comment]
Setting the `margin` on the `:host` is a quicker way to ensure that gap from the viewport.
Probably this could be done as well by setting `max-width: calc(100vw - 48px);`... I'll experiment with this.

**Comment by valdrinkoshi** [comment]
Ok, so the problem is not really caused by setting `margin: 24px 40px`, but by
```css
      :host > ::content > * {
        margin-top: 20px;
        padding: 0 24px;  /* this one causes the padding left/right */
      }

      :host > ::content > .no-padding {
        padding: 0;
      }

      :host > ::content > *:first-child {
        margin-top: 24px; /* this one causes the margin top */
      }
```

This is done to give enough vertical & horizontal room to each child of the `paper-dialog`. 
I'm not sure why we've chosen to set `padding` instead of `margin` for the horizontal space though.

At this point, changing these styles would be a breaking change, so I'd recommend we suggest to Polymer users to set the proper styles:
```html
<style is="custom-style">
  paper-dialog > paper-toolbar {
    margin: 0;
    padding: 0;
  };
</style>

<paper-dialog>
  <paper-toolbar>
    <paper-button>menu</paper-button>
    <h2 class="title">Title</h2>
  </paper-toolbar>
</paper-dialog>
